name: Publish

on:
  push:
    branches: [main]

permissions: read-all

jobs:
  build:
    name: "Build storybook static code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Storybook
        run: |
          npm ci
          npm run storybook-build-static

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build/storybook
          retention-days: 1

  deploy:
    name: "Deploy storybook on GitHub pages"
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2